# -*- coding: utf-8 -*-
"""PFO_Original.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q7V5ZYYye9yQVYcs3hnwUySqxy4fAo-o
"""

import random
import time
import math
import numpy as np
import numpy
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from copy import deepcopy
import warnings
warnings.filterwarnings('ignore')
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import KFold 
from sklearn import metrics
from sklearn.metrics import confusion_matrix, make_scorer, classification_report
from sklearn.model_selection import cross_validate
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score, accuracy_score
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import precision_score, recall_score
import seaborn as sns # data visualization library

"""Accuracy And Other Parameters"""

# Classification Accuracy , Precision and Recall
def classification_accuracy(y_actual, y_hat):
        TP = 0
        FP = 0
        TN = 0
        FN = 0

        for i in range(len(y_hat)): 
            if y_actual[i]==y_hat[i]==1:
                TP += 1
            if y_hat[i]==1 and y_actual[i]!=y_hat[i]:
                FP += 1
            if y_actual[i]==y_hat[i]==0:
                TN += 1
            if y_hat[i]==0 and y_actual[i]!=y_hat[i]:
                FN += 1
        
        
        class_acc = float((TP+TN)) / float((TP+FP+TN+FN))
        
        if TP == 0 and FN == 0 :
            recall = 0
        else:
            recall  = float(TP) / float(TP + FN)
        
        if TP == 0 and FP == 0:
            precision = 0
        else:
            precision = float(TP) / float( TP + FP )         
        
        if TN == 0 and FP == 0 :
          specificity = 0
        else:
          specificity = float(TN) / float(TN + FP)  

        f1_score = float(2 * precision * recall) / float(precision + recall)

        if TP == 0 and TN == 0 and FN ==0 and FP == 0 :
          kappa = 0
        else:
          kappa = float(2 * (TP * TN - FN * FP)) / float((TP + FP) * (FP + TN) + (TP + FN) * (FN + TN))

        if TP == 0 and TN == 0 and FN ==0 and FP == 0 :
          MCC = 0
        else:
          MCC = float(TP * TN - FN * FP) / float(math.sqrt((TP + FP) * (FP + TN) * (TP + FN) * (FN + TN)))    

        return (class_acc,specificity, recall, precision,f1_score,kappa,MCC)

"""Read Dataset and Split into input and output"""

data = pd.read_csv('/content/breast_cancer.csv')
data = data.drop(columns=["id"])
#data = data.drop(columns=["sex"])
#data = data.drop(columns=["re0erral_source"])
X = data.drop(columns=["diagnosis"])
Y = data['diagnosis']

"""Without Optimization

1. Train-Test Method - Logistic Regression
"""

label = LabelEncoder()
y = label.fit_transform(Y)
y[:20]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

#By Logistic Regression

print("By Logistic Regression")
print()

LR = LogisticRegression()
LR.fit(X_train, y_train)
LR.score(X_train, y_train)
y_pred = LR.predict(X_test)
y_pred_train = LR.predict(X_train)

AllValues = classification_accuracy(y_test, y_pred)
error=100-(AllValues[0]*100)
#Accuracy Inbuilt Function
#a1 = accuracy_score(y_test, y_pred)
#print(a1)
print("Allvalues - ",AllValues)
print()
print("Accuracy without Optimization : ", AllValues[0] * 100)

print()
print("ROC CURVE:-")
y_pred_logistic = LR.decision_function(X_test)
logistic_fpr, logistic_tpr, threshold = roc_curve(y_test, y_pred_logistic)
auc_logistic = auc(logistic_fpr, logistic_tpr)
plt.figure(figsize=(5, 5), dpi=80)
plt.plot(logistic_fpr, logistic_tpr, marker='.', label='Logistic (auc = %0.3f)' % auc_logistic)
plt.xlabel('False Positive Rate -->')
plt.ylabel('True Positive Rate -->')
plt.title('ROC Curve - Train-Test By Logistic Regression')
plt.legend()
plt.show()

rc2 = roc_auc_score(y_test, y_pred) 
print()
print("Roc Curve Score - ",rc2)
print()
print("Confusion Matrix Train Test by Logistic Regression : ")
cm_2 = confusion_matrix(y_test, y_pred)
sns.heatmap(cm_2,annot=True,fmt="d")

"""2. K-Fold Method - Logistic Regression"""

#X1Fold = data.drop(columns=["Target"])
#Y1Fold = data['Target']
X1Fold = X
Y1Fold = data['diagnosis']

# Logistic Regression
print("By Logistic Regression")
print()

LR = LogisticRegression()
k = 10
timerStart=time.time() 
kf = KFold(n_splits=k, random_state=None)
LR.fit(X1Fold,Y1Fold)
visualizer = cross_val_score(LR, X1Fold, Y1Fold, cv = kf)
y_pred = cross_val_predict(LR, X1Fold, Y1Fold, cv = kf)
y_actual = y
y_predict = y_pred

#Accuracy Inbuilt Function
#a1 = accuracy_score(Y1Fold, y_pred)
#print(a1)
AllValues1 = classification_accuracy(Y1Fold, y_pred)
error=100-(AllValues1[0]*100)
print("Allvalues - ",AllValues1)
print()
print("Accuracy without Optimization : ", AllValues1[0] * 100)
print()

print("ROC CURVE:-")
print()
logistic = auc(logistic_fpr, logistic_tpr)
plt.figure(figsize=(5, 5), dpi=80)
plt.plot(logistic_fpr, logistic_tpr, marker='.', label='Logistic (auc = %0.3f)' % auc_logistic)
plt.xlabel('False Positive Rate -->')
plt.ylabel('True Positive Rate -->')
plt.title# Code for ROC_AUC curve
y_pred_logistic = LR.decision_function(X1Fold)
logistic_fpr, logistic_tpr, threshold = roc_curve(Y1Fold, y_pred)
plt.title('ROC Curve - K-Fold By Logistic Regression')
plt.legend()
plt.show()
print()

rck1 = roc_auc_score(Y1Fold, y_pred)
print("Roc Curve Score - ",rck1)
print()

print("Confusion Matrix K-Fold by Logistic Regression : ")
cm_2 = confusion_matrix(Y1Fold, y_pred)               
sns.heatmap(cm_2,annot=True,fmt="d")

"""Optimization -"""

#data=data.drop(columns=['Target'])
#val=data.values
data = data.drop(columns=["diagnosis"])

class RootAlgo(object):
    """ This is root of all Algorithms """
    ID_MIN_PROBLEM = 0
    ID_MAX_PROBLEM = -1

    def __init__(self, root_algo_paras = None):
        self.problem_size = root_algo_paras["problem_size"]
        self.domain_range = root_algo_paras["domain_range"]
        self.print_train = root_algo_paras["print_train"]
        self.objective_func = root_algo_paras["objective_func"]
        self.solution, self.loss_train = None, []

    def _create_solution__(self, count, minmax=0):
        solution = np.random.uniform(self.domain_range[0], self.domain_range[1], self.problem_size)
        fitness= self._fitness_model__(solution=solution, minmax=minmax)
        return [solution, fitness]

    def _fitness_model__(self, solution=None, minmax=0):
        """ Assumption that objective function always return the original value """
        return self.objective_func(solution, self.problem_size) if minmax == 0 \
            else 1.0 / self.objective_func(solution, self.problem_size)

    def _fitness_encoded__(self, encoded=None, id_pos=None, minmax=0):
        return self._fitness_model__(solution=encoded[id_pos], minmax=minmax)

    def _get_global_best__(self, pop=None, id_fitness=None, id_best=None):
        sorted_pop = sorted(pop, key=lambda temp: temp[id_fitness])
        return deepcopy(sorted_pop[id_best])

    def _get_global_worst__(self, pop=None, id_fitness=None, id_worst=None):
        sorted_pop = sorted(pop, key=lambda temp: temp[id_fitness])
        return deepcopy(sorted_pop[id_worst])

    def _amend_solution__(self, solution=None):
        for i in range(self.problem_size):
            if solution[i] < self.domain_range[0]:
                solution[i] = self.domain_range[0]
            if solution[i] > self.domain_range[1]:
                solution[i] = self.domain_range[1]

    def _amend_solution_and_return__(self, solution=None):
        for i in range(self.problem_size):
            if solution[i] < self.domain_range[0]:
                solution[i] = self.domain_range[0]
            if solution[i] > self.domain_range[1]:
                solution[i] = self.domain_range[1]
        return solution

    def _create_opposition_solution__(self, solution=None, g_best=None):
        temp = [self.domain_range[0] + self.domain_range[1] - g_best[i] + np.random.random() * (g_best[i] - solution[i])
                      for i in range(self.problem_size)]
        return np.array(temp)


    def _train__(self):
        pass

"""Path-Finder Optimization Algorithm :-"""

class BasePFA(RootAlgo):
    """
    A new meta-heuristic optimizer: Pathfinder algorithm
    """
    ID_POS = 0
    ID_FIT = 1

    def __init__(self, root_algo_paras=None, pfa_paras = None):
        RootAlgo.__init__(self, root_algo_paras)
        self.epoch = pfa_paras["epoch"]
        self.pop_size = pfa_paras["pop_size"]
        self.best = None

    def _train__(self):
        global features
        timerStart=time.time()
        # Init pop and calculate fitness
        pop = [self._create_solution__(i, minmax=0) for i in range(self.pop_size)]

        # Find the pathfinder
        pop = sorted(pop, key=lambda temp: temp[self.ID_FIT])
        
        for i in range(self.pop_size):
          self.best = self._create_solution__(i,minmax=0)[1][1]
          features[self.best]=1
        g_best = deepcopy(pop[0])
        gbest_present = deepcopy(g_best)

        for i in range(self.epoch):
            alpha, beta = np.random.uniform(1, 2, 2)
            A = np.random.uniform(self.domain_range[0], self.domain_range[1]) * np.exp(-2 * (i + 1) / self.epoch)

            ## Update the position of pathfinder and check the bound
            temp = gbest_present[self.ID_POS] + 2 * np.random.uniform() * (gbest_present[self.ID_POS] - g_best[self.ID_POS]) + A
            temp = self._amend_solution_and_return__(temp)
            fit = self._fitness_model__(temp)
            g_best = deepcopy(gbest_present)
            if fit < gbest_present[self.ID_FIT]:
                gbest_present = [temp, fit]
            pop[0] = deepcopy(gbest_present)

            ## Update positions of members, check the bound and calculate new fitness
            for j in range(1, self.pop_size):
                temp1 = deepcopy(pop[j][self.ID_POS])
                temp2 = deepcopy(pop[j][self.ID_POS])

                t1 = beta * np.random.uniform() * (gbest_present[self.ID_POS] - temp1)
                for k in range(1, self.pop_size):
                    dist = np.linalg.norm(pop[k][self.ID_POS] - temp1)
                    t2 = alpha * np.random.uniform() * (pop[k][self.ID_POS] - temp1)
                    t3 = np.random.uniform(self.domain_range[0], self.domain_range[1], self.problem_size) * (1 - (i + 1) * 1.0 / self.epoch) * dist
                    temp2 += t2 + t3
                temp2 += t1

                ## Update members
                temp2 = self._amend_solution_and_return__(temp2)
                fit = self._fitness_model__(temp2)
                if fit < pop[j][self.ID_FIT]:
                    pop[j] = [temp2, fit]

            ## Update the best solution found so far (current pathfinder)
            current_best = self._get_global_best__(pop, self.ID_FIT, self.ID_MIN_PROBLEM)
            if current_best[self.ID_FIT] < gbest_present[self.ID_FIT]:
                gbest_present = deepcopy(current_best)

            self.loss_train.append(gbest_present[self.ID_FIT])
        #     if self.print_train:
        #         print("Generation : {0}, best result so far: {1}".format(i + 1, gbest_present[self.ID_FIT]))

        # return gbest_present[self.ID_FIT], self.loss_train
        for j in range(0, self.epoch):
          pass
        timerEnd=time.time()  
        executionTime=timerEnd-timerStart
        print("Execution Time: ",executionTime)
        return self.loss_train[-1]

"""Objective Function : Sphere Function"""

#objective function

def square_function(solution=None, problem_size=None):
  """ Sphere Function """
  fitness=[(solution[i] ** 2)/(10 ** 5) for i in range(0, problem_size)]
  Best=fitness.index(min(fitness))
  return sum(fitness),Best

"""Setting Parameters"""

## Setting parameters
root_paras = {
    "problem_size": 30,
    "domain_range": [-10, 10],
    "print_train": True,
    "objective_func": square_function
}
pfa_paras = {
    "epoch": 500,
    "pop_size": 30
}

"""Run Path-Finder Optimization"""

features=[0]*root_paras["problem_size"]
md = BasePFA(root_algo_paras=root_paras, pfa_paras=pfa_paras)
print("The best fitness is: ",md._train__())
modified_daata=pd.DataFrame()
for i in range(len(features)):
    if features[i]==1:
        modified_daata[data.columns[i]]=data[data.columns[i]].astype(float)
#print("The modified data is following")
modified_daata.head()
#print(modified_daata)

"""Optimized Data Information"""

modified_daata.info()
print()

"""Train Test Method After Optimization"""

label = LabelEncoder()
X0 = modified_daata
Y0 = label.fit_transform(Y)
Y0[:20]


X_train0, X_test0, y_train0, y_test0 = train_test_split(X0, Y0, test_size = 0.3)
X_train0.shape, X_test0.shape, y_train0.shape, y_test0.shape

"""1. Logisitic Regression"""

#By Logistic Regression

print("By Logistic Regression")
print()

timerStart=time.time() 

LR = LogisticRegression()
LR.fit(X_train0, y_train0)
LR.score(X_train0, y_train0)
y_pred0 = LR.predict(X_test0)
y_pred_train0 = LR.predict(X_train0)
#Accuracy Inbuilt Function
#a10 = accuracy_score(y_test0, y_pred0)
#print(a1)
AllValues10 = classification_accuracy(y_test0, y_pred0)
error=100-(AllValues10[0]*100)

print("Allvalues - ",AllValues10)
print()
print("Accuracy after Optimization : ", AllValues10[0] * 100)
print()

print("ROC CURVE:-")
y_pred_logistic0 = LR.decision_function(X_test0)
logistic_fpr0, logistic_tpr0, threshold0 = roc_curve(y_test0, y_pred_logistic0)
auc_logistic0 = auc(logistic_fpr0, logistic_tpr0)
plt.figure(figsize=(5, 5), dpi=80)
plt.plot(logistic_fpr0, logistic_tpr0, marker='.', label='Logistic (auc = %0.3f)' % auc_logistic0)
plt.xlabel('False Positive Rate -->')
plt.ylabel('True Positive Rate -->')
plt.title('ROC Curve - Train-Test By Logistic Regression')
plt.legend()
plt.show()

rc20 = roc_auc_score(y_test0, y_pred0) 
print()
print("Roc Curve Score - ",rc20)
print()
timerEnd=time.time()
print("Execution Time: ",timerEnd-timerStart)
print("Confusion Matrix Train Test by Logistic Regression : ")
cm_20 = confusion_matrix(y_test0, y_pred0)
sns.heatmap(cm_20,annot=True,fmt="d")

"""2. Decision Tree"""

#BY Decision Tree

print("By Decision tree")
print()

DecisionTree = tree.DecisionTreeClassifier(max_depth=5,min_samples_leaf=15)
timerStart=time.time() 
DecisionTree.fit(X_train0, y_train0)
y_pred1 = DecisionTree.predict(X_test0)
y_pred_train1 = DecisionTree.predict(X_train0)

#Accuracy Inbuilt Function
#DT_acc0 = accuracy_score(y_test0, y_pred1)
#print("Accuracy of test data by inbuilt formula = ",DT_acc0*100)

AllValues11 = classification_accuracy(y_test0, y_pred1)
error=100-(AllValues11[0]*100)

print("Allvalues - ",AllValues11)
print()
print("Accuracy after Optimization : ", AllValues11[0] * 100)
print()

# Code for ROC_AUC curve
y_pred_dt = DecisionTree.predict_proba(X_test0)    
y_pred_dt = y_pred_dt[:, 1]  
dt_fpr, dt_tpr, threshold = roc_curve(y_test0, y_pred_dt)
auc_dtree = auc(dt_fpr, dt_tpr)
plt.figure(figsize=(5, 5), dpi=80)
plt.plot(dt_fpr, dt_tpr, linestyle='-', label='Decision Tree (auc = %0.3f)' % auc_dtree)
plt.xlabel('False Positive Rate -->')
plt.ylabel('True Positive Rate -->')
plt.title('ROC Curve - Train-Test By Decision Tree')
plt.legend()
plt.show()

rc21 = roc_auc_score(y_test0, y_pred1)    
print()
print("Roc Curve Score - ",rc21)
print()
timerEnd=time.time()
print("Execution Time: ",timerEnd-timerStart)
print("Confusion Matrix Train Test by Decision Tree : ")

cm_2 = confusion_matrix(y_test0, y_pred1)           
sns.heatmap(cm_2,annot=True,fmt="d")

"""3. KNN"""

print("By KNN")
print()

timerStart=time.time() 
error_rate = []
for i in range(1,42):
  knn = KNeighborsClassifier(n_neighbors=i)
  knn.fit(X_train0, y_train0)
  pred_i = knn.predict(X_test0)
  error_rate.append(numpy.mean(pred_i != y_test0))

plt.figure(figsize=(12,6))        
plt.plot(range(1,42), error_rate, color='purple', linestyle="--",marker='o', markersize=10, markerfacecolor='b')
plt.title('Error_Rate vs K-value')
plt.show()


knn = KNeighborsClassifier(n_neighbors=9)
knn.fit(X_train0, y_train0)
knn.score(X_train0, y_train0)
y_pred2 = knn.predict(X_test0)
y_pred_train2 = knn.predict(X_train0)
# find accuracy
#ac = accuracy_score(y_test0, y_pred2)
#print(ac)

AllValues12 = classification_accuracy(y_test0, y_pred2)
error=100-(AllValues12[0]*100)

print()
print("Allvalues - ",AllValues12)
print()
print("Accuracy after Optimization : ", AllValues12[0] * 100)
print()

# Code for ROC_AUC curve
y_pred_knn = knn.predict_proba(X_test0)    
y_pred_knn = y_pred_knn[:, 1]  
knn_fpr, knn_tpr, threshold = roc_curve(y_test0, y_pred_knn)
auc_knn = auc(knn_fpr, knn_tpr)
plt.figure(figsize=(5, 5), dpi=80)
plt.plot(knn_fpr, knn_tpr, linestyle='-', label='K Nearest Neighbor (auc = %0.3f)' % auc_knn)
plt.xlabel('False Positive Rate -->')
plt.ylabel('True Positive Rate -->')
plt.title('ROC Curve - Train-Test By KNN')
plt.legend()
plt.show()

print()
rc22 = roc_auc_score(y_test0, y_pred2)   
print("Roc Curve Score - ",rc21)
print()
timerEnd=time.time()

print("Execution Time: ",timerEnd-timerStart)
print("Confusion Matrix Train Test by KNN : ")
cm_22 = confusion_matrix(y_test0, y_pred2)               
sns.heatmap(cm_22,annot=True,fmt="d")

#print(classification_report(y_test0, y_pred2))

"""4. SVM"""

#By SVM
print("BY SVM")
print()

svc_model = SVC(kernel="rbf")
timerStart=time.time()
svc_model.fit(X_train0, y_train0)
svc_model.score(X_train0, y_train0)
y_pred3 = svc_model.predict(X_test0)
y_pred_train3 = svc_model.predict(X_train0)

sc = StandardScaler()
X_train10 = sc.fit_transform(X_train0)
X_test10 = sc.transform(X_test0)
svcclassifier = SVC(kernel = 'rbf', random_state = 50)
svcclassifier.fit(X_train10, y_train0)
y_pred31 = svcclassifier.predict(X_test10)
y_pred311 = svcclassifier.predict(X_train10)

# find accuracy
#ac = accuracy_score(y_test0, y_pred3)
#print(ac)
#ac1 = ac = accuracy_score(y_test0, y_pred31)
#print(ac1)

AllValues13 = classification_accuracy(y_test0, y_pred31)
error=100-(AllValues13[0]*100)

print("Allvalues - ",AllValues13)
print()
print("Accuracy after Optimization : ", AllValues13[0] * 100)
print()

# Code for ROC_AUC curve
y_pred_svm = svc_model.decision_function(X_test0)
svm_fpr, svm_tpr, threshold = roc_curve(y_test0, y_pred_svm)
auc_svm = auc(svm_fpr, svm_tpr)
plt.figure(figsize=(5, 5), dpi=80)
plt.plot(svm_fpr, svm_tpr, linestyle='-', label='SVM (auc = %0.3f)' % auc_svm)
plt.xlabel('False Positive Rate -->')
plt.ylabel('True Positive Rate -->')
plt.title('ROC Curve - Train-Test By SVM')
plt.legend()
plt.show()

# Code for ROC_AUC curve
rc23 = roc_auc_score(y_test0, y_pred31)    
print("Roc Curve Score - ",rc21)
print()   
timerEnd=time.time()

print("Execution Time: ",timerEnd-timerStart)
print("Confusion Matrix Train Test by SVM : ")
cm_23 = confusion_matrix(y_test0, y_pred31)              
sns.heatmap(cm_23,annot=True,fmt="d")

"""5. Ensemble"""

#By Ensemble
print("BY Ensemble")
print()

rfc = RandomForestClassifier(n_estimators=300)
timerStart=time.time()
rfc.fit(X_train0, y_train0)
rfc.score(X_train0, y_train0)
y_pred4 = rfc.predict(X_test0)
y_pred_train4 = rfc.predict(X_train0)

# find accuracy
#ac = accuracy_score(y_test0, y_pred4)
#print(ac)

AllValues14 = classification_accuracy(y_test0, y_pred4)
error=100-(AllValues14[0]*100)

print("Allvalues - ",AllValues14)
print()
print("Accuracy after Optimization : ", AllValues14[0] * 100)
print()

# Code for ROC_AUC curve
y_pred_rfc = rfc.predict_proba(X_test0)    
y_pred_rfc = y_pred_rfc[:, 1]  
rfc_fpr, rfc_tpr, threshold = roc_curve(y_test0, y_pred_rfc)
auc_rfc = auc(rfc_fpr, rfc_tpr)
plt.figure(figsize=(5, 5), dpi=80)
plt.plot(rfc_fpr, rfc_tpr, linestyle='-', label='Random Forest (auc = %0.3f)' % auc_rfc)
plt.xlabel('False Positive Rate -->')
plt.ylabel('True Positive Rate -->')
plt.title('ROC Curve - Train-Test By Ensemble')
plt.legend()
plt.show()

# Code for ROC_AUC curve
rc24 = roc_auc_score(y_test0, y_pred4)    
print("Roc Curve Score - ",rc24)
print()   
timerEnd=time.time()

print("Execution Time: ",timerEnd-timerStart)
print("Confusion Matrix Train Test by Ensemble : ")
cm_24 = confusion_matrix(y_test0, y_pred4)              
sns.heatmap(cm_24,annot=True,fmt="d")

"""Merge ROC Curve"""

#Combined ROC Curve
plt.figure(figsize=(5, 5), dpi=60)
plt.plot(svm_fpr, svm_tpr, linestyle='-', label='SVM (auc = %0.3f)' % auc_svm)
plt.plot(logistic_fpr, logistic_tpr, marker='.', label='Logistic (auc = %0.3f)' % auc_logistic)
plt.plot(rfc_fpr, rfc_tpr, linestyle='-', label='Random Forest (auc = %0.3f)' % auc_rfc)
plt.plot(dt_fpr, dt_tpr, linestyle='-', label='Decision Tree (auc = %0.3f)' % auc_dtree)
plt.plot(knn_fpr, knn_tpr, linestyle='-', label='K Nearest Neighbor (auc = %0.3f)' % auc_knn)
plt.plot(rfc_fpr, rfc_tpr, linestyle='-', label='Random Forest (auc = %0.3f)' % auc_rfc)
plt.xlabel('False Positive Rate -->')
plt.ylabel('True Positive Rate -->')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend()
plt.show()

"""K-Fold Method After Optimization"""

X1Fold0 = modified_daata
Y1Fold0 = Y

"""1. Logistic Regression"""

# Logistic Regression
print("By Logistic Regression")
print()

LR = LogisticRegression()
k = 10
timerStart=time.time() 
kf = KFold(n_splits=k, random_state=None)
LR.fit(X1Fold0,Y1Fold0)
visualizer = cross_val_score(LR, X1Fold0, Y1Fold0, cv = kf)
y_pred20 = cross_val_predict(LR, X1Fold0, Y1Fold0, cv = kf)
y_actual = y
y_predict = y_pred

#Accuracy Inbuilt Function
#a1 = accuracy_score(Y1Fold, y_pred)
#print(a1)
AllValues51 = classification_accuracy(Y1Fold0, y_pred20)
error=100-(AllValues51[0]*100)
print("Allvalues - ",AllValues51)
print()
print("Accuracy After Optimization : ", AllValues51[0] * 100)
print()

print("ROC CURVE:-")
print()
logistic = auc(logistic_fpr, logistic_tpr)
plt.figure(figsize=(5, 5), dpi=80)
plt.plot(logistic_fpr, logistic_tpr, marker='.', label='Logistic (auc = %0.3f)' % auc_logistic)
plt.xlabel('False Positive Rate -->')
plt.ylabel('True Positive Rate -->')
plt.title# Code for ROC_AUC curve
y_pred_logistic = LR.decision_function(X1Fold0)
logistic_fpr, logistic_tpr, threshold = roc_curve(Y1Fold0, y_pred20)
plt.title('ROC Curve - K-Fold By Logistic Regression')
plt.legend()
plt.show()
print()

rck10 = roc_auc_score(Y1Fold, y_pred20)
print("Roc Curve Score - ",rck10)
print()
timerEnd=time.time()

print("Execution Time: ",timerEnd-timerStart)
print("Confusion Matrix K-Fold by Logistic Regression : ")
cm_201 = confusion_matrix(Y1Fold0, y_pred20)               
sns.heatmap(cm_201,annot=True,fmt="d")

"""2. Decision Tree"""

#Decision Tree
print("By Decision Tree")
print()

DecisionTree = tree.DecisionTreeClassifier(max_depth=3,min_samples_leaf=12)
timerStart=time.time() 
k = 10
DecisionTree.fit(X1Fold0,Y1Fold0)
kf = KFold(n_splits=k, random_state=None)
visualizer = cross_val_score(DecisionTree, X1Fold0, Y1Fold0, cv = kf)
y_pred21 = cross_val_predict(DecisionTree, X1Fold0, Y1Fold0, cv = kf)

#Accuracy
#DecisionTree_acc = accuracy_score(Y1Fold0, y_pred21)
#print(DecisionTree_acc)

AllValues52 = classification_accuracy(Y1Fold0, y_pred21)
error=100-(AllValues52[0]*100)
print("Allvalues - ",AllValues52)
print()
print("Accuracy After Optimization : ", AllValues52[0] * 100)
print()

print("ROC CURVE:-")
print()
dt_fpr, dt_tpr, threshold = roc_curve(Y1Fold0, y_pred21)
auc_dtree = auc(dt_fpr, dt_tpr)
plt.figure(figsize=(5, 5), dpi=80)
plt.plot(dt_fpr, dt_tpr, linestyle='-', label='Decision Tree (auc = %0.3f)' % auc_dtree)
plt.xlabel('False Positive Rate -->')
plt.ylabel('True Positive Rate -->')
plt.title('ROC Curve - K-Fold By Decision Tree')
plt.legend()
plt.show()


rck11 = roc_auc_score(Y1Fold0, y_pred21)
print("Roc Curve Score - ",rck11)
print()
timerEnd=time.time()

print("Execution Time: ",timerEnd-timerStart)
print("Confusion Matrix K-Fold by Decision Tree : ")
cm_202 = confusion_matrix(Y1Fold0, y_pred21)               
sns.heatmap(cm_202,annot=True,fmt="d")

"""3. KNN"""

print("By KNN")
print()


knn = KNeighborsClassifier(n_neighbors=9)
k = 10
timerStart=time.time() 
kf = KFold(n_splits=k, random_state=None)
visualizer = cross_val_score(knn, X1Fold0, Y1Fold0, cv = kf)
y_pred22 = cross_val_predict(knn, X1Fold0, Y1Fold0, cv = kf)

#Accuracy
#DecisionTree_acc = accuracy_score(Y1Fold0, y_pred21)
#print(DecisionTree_acc)

AllValues53 = classification_accuracy(Y1Fold0, y_pred22)
error=100-(AllValues53[0]*100)
print("Allvalues - ",AllValues53)
print()
print("Accuracy After Optimization : ", AllValues53[0] * 100)
print()

knn_fpr, knn_tpr, threshold = roc_curve(Y1Fold0, y_pred22)
auc_knn = auc(knn_fpr, knn_tpr)
plt.figure(figsize=(5, 5), dpi=80)
plt.plot(knn_fpr, knn_tpr, linestyle='-', label='K Nearest Neighbors (auc = %0.3f)' % auc_knn)
plt.xlabel('False Positive Rate -->')
plt.ylabel('True Positive Rate -->')
plt.title('ROC Curve - K-Fold By KNN')
plt.legend()
plt.show()


rck12 = roc_auc_score(Y1Fold0, y_pred22)
print("Roc Curve Score - ",rck12)
print()
timerEnd=time.time()

print("Execution Time: ",timerEnd-timerStart)
print("Confusion Matrix K-Fold by KNN : ")
cm_203 = confusion_matrix(Y1Fold0, y_pred22)               
sns.heatmap(cm_203,annot=True,fmt="d")

"""4. SVM"""

print("By SVM")
print()

svc = SVC(kernel="rbf")
k = 10
timerStart=time.time()
svc.fit(X1Fold0, Y1Fold0)
kf = KFold(n_splits=k, random_state=None)
visualizer = cross_val_score(svc, X1Fold0, Y1Fold0, cv = kf)
y_pred23 = cross_val_predict(svc,X1Fold0, Y1Fold0, cv = kf)

sc = StandardScaler()
X_train10 = sc.fit_transform(X1Fold0)
X_test10 = sc.transform(X1Fold0)
svcclassifier = SVC(kernel = 'rbf', random_state = 50)
svcclassifier.fit(X1Fold0, Y1Fold0)
y_pred231 = svcclassifier.predict(X1Fold0)
y_pred_train231 = svcclassifier.predict(X1Fold0)

#Accuracy
#DecisionTree_acc = accuracy_score(Y1Fold0, y_pred21)
#print(DecisionTree_acc)

AllValues54 = classification_accuracy(Y1Fold0, y_pred231)
error=100-(AllValues54[0]*100)
print("Allvalues - ",AllValues54)
print()
print("Accuracy After Optimization : ", AllValues54[0] * 100)
print()
print("ROC - Curve")

# Code for ROC_AUC curve
y_pred_svm = svc.decision_function(X_test10)
svm_fpr, svm_tpr, threshold = roc_curve(Y1Fold0, y_pred23)
auc_svm = auc(svm_fpr, svm_tpr)

plt.figure(figsize=(5, 5), dpi=80)
plt.plot(svm_fpr, svm_tpr, linestyle='-', label='SVM (auc = %0.3f)' % auc_svm)

plt.xlabel('False Positive Rate -->')
plt.ylabel('True Positive Rate -->')
plt.title('ROC Curve - K-Fold By SVM')
plt.legend()
plt.show()


rck13 = roc_auc_score(Y1Fold0, y_pred231)
print("Roc Curve Score - ",rck13)
print()
timerEnd=time.time()

print("Execution Time: ",timerEnd-timerStart)
print("Confusion Matrix K-Fold by SVM : ")
cm_204 = confusion_matrix(Y1Fold0, y_pred231)               
sns.heatmap(cm_204,annot=True,fmt="d")

"""Ensemble"""

print("By Ensemble")
print()

rfc = RandomForestClassifier(n_estimators=300)
k = 10
timerStart=time.time()
kf = KFold(n_splits=k, random_state=None)
visualizer = cross_val_score(rfc,  X1Fold0, Y1Fold0, cv = kf)
y_pred24 = cross_val_predict(rfc, X1Fold0, Y1Fold0, cv = kf)

#Accuracy
#acc = accuracy_score(Y1Fold0, y_pred24)
#print(acc)

AllValues55 = classification_accuracy(Y1Fold0, y_pred24)
error=100-(AllValues55[0]*100)
print("Allvalues - ",AllValues55)
print()
print("Accuracy After Optimization : ", AllValues55[0] * 100)
print()
print("ROC - Curve")

# Code for ROC_AUC curve
rfc_fpr, rfc_tpr, threshold = roc_curve(Y1Fold0, y_pred24)
auc_rfc = auc(rfc_fpr, rfc_tpr)

plt.figure(figsize=(5, 5), dpi=80)
plt.plot(rfc_fpr, rfc_tpr, linestyle='-', label='Random Forest (auc = %0.3f)' % auc_rfc)
plt.xlabel('False Positive Rate -->')
plt.ylabel('True Positive Rate -->')
plt.title('ROC Curve - K-Fold By Ensemble')
plt.legend()
plt.show()

rck14 = roc_auc_score(Y1Fold0, y_pred24)
print("Roc Curve Score - ",rck14)
print()
timerEnd=time.time()

print("Execution Time: ",timerEnd-timerStart)
print("Confusion Matrix K-Fold by Ensemble : ")
cm_205 = confusion_matrix(Y1Fold0, y_pred24)               
sns.heatmap(cm_205,annot=True,fmt="d")

"""Merge ROC Curve"""

#Combined ROC Curve
plt.figure(figsize=(5, 5), dpi=60)
plt.plot(svm_fpr, svm_tpr, linestyle='-', label='SVM (auc = %0.3f)' % auc_svm)
plt.plot(logistic_fpr, logistic_tpr, marker='.', label='Logistic (auc = %0.3f)' % auc_logistic)
plt.plot(rfc_fpr, rfc_tpr, linestyle='-', label='Random Forest (auc = %0.3f)' % auc_rfc)
plt.plot(dt_fpr, dt_tpr, linestyle='-', label='Decision Tree (auc = %0.3f)' % auc_dtree)
plt.plot(knn_fpr, knn_tpr, linestyle='-', label='K Nearest Neighbor (auc = %0.3f)' % auc_knn)
plt.plot(rfc_fpr, rfc_tpr, linestyle='-', label='Random Forest (auc = %0.3f)' % auc_rfc)
plt.xlabel('False Positive Rate -->')
plt.ylabel('True Positive Rate -->')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend()
plt.show()